<% if_link("http_backend") do |backend| -%>
http:
  routers:
<% if p('traefik.tls.enabled') -%>
    autoconf-https:
      tls: {}
      rule: "HostRegexp(`{dummy:[-.[:alnum:]_]+}`)"
      service: autoconf
      priority: <%= p('traefik.autoconf.priority') %>
      entryPoints:
      - web-secure
<% end -%>
<% if p('traefik.http.enabled') -%>
    autoconf-http:
      rule: "HostRegexp(`{dummy:[-.[:alnum:]_]+}`)"
      service: autoconf
      priority: <%= p('traefik.autoconf.priority') %>
      entryPoints:
      - web
<% end -%>

  services:
    autoconf:
      loadBalancer:
        servers:
        <% backend.instances.each_with_index do |instance,i| -%> 
        - url: "http://<%= instance.address %>:<%= p("traefik.auto_conf.http_port") %>"
        <% end -%>
<% if p("traefik.auto_conf.health_check.enabled") == true -%>

        healthCheck:
          path:  <%= p("traefik.auto_conf.health_check.path") %>
          interval: <%= p("traefik.auto_conf.health_check.interval") %>
          timeout: <%=  p("traefik.auto_conf.health_check.timeout") %>
          scheme: <%=  p("traefik.auto_conf.health_check.scheme") %>
          port: <%=  p(["traefik.auto_conf.health_check.port","traefik.auto_conf.http_port"]) %>
<% end -%>
<% end -%>
